CREATE PROCEDURE SP_ActualizarDatosProductor
    @NombreProductor nchar(50),
	@NombreActor nchar(35)
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @LastID INT
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	BEGIN TRANSACTION
	
	BEGIN TRY
		INSERT INTO Actores VALUES ('PRUEBA')
		SET @LastID = @@IDENTITY
		INSERT INTO Productores VALUES ('PRUEBA', 'P')
		COMMIT
	END TRY
	BEGIN CATCH
			WAITFOR DELAY '00:00:15'
			ROLLBACK
	END CATCH
END
RETURN 0
GO