CREATE PROCEDURE SP_ConsultarActores
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	BEGIN TRANSACTION
	
	BEGIN TRY
		SELECT * FROM dbo.Actores
		WAITFOR DELAY '00:00:05'
		SELECT * FROM dbo.Actores
		COMMIT
	END TRY
	BEGIN CATCH
			ROLLBACK
	END CATCH	
END
RETURN 0
GO 

EXEC SP_ConsultarActores