CREATE PROCEDURE SP_ConsultarActores
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	BEGIN TRANSACTION
	
	BEGIN TRY
		select * from Productores
		COMMIT
	END TRY
	BEGIN CATCH
			ROLLBACK
	END CATCH	
END
RETURN 0
GO