-- Correr segundo
CREATE PROCEDURE [dbo].[SP_ConsultarActores]
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED -- COMMITTED
	BEGIN TRANSACTION
	
	BEGIN TRY
		SELECT * FROM Actores
		WAITFOR DELAY '00:00:05'
		SELECT * FROM Actores
		COMMIT
	END TRY
	BEGIN CATCH
			ROLLBACK
	END CATCH	
END
RETURN 0
GO 

USE esencialVerde
EXEC SP_ConsultarActores