CREATE PROCEDURE SP_ConsultarResiduos
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED
	BEGIN TRANSACTION
	
	BEGIN TRY
		SELECT * FROM Residuos
		WAITFOR DELAY '00:00:10'
		SELECT * FROM Residuos
		COMMIT
	END TRY
	BEGIN CATCH
			ROLLBACK
	END CATCH	
END
RETURN 0
GO

EXEC SP_ConsultarResiduos